# Why NumPy ?

## Verimliliği arttırmak için kullanılıyor.OOP mantığıyla fazla yer kaplıyor.

In [19]:
a =[1,2,3,4]
b = [5,6,4,9]
a

[1, 2, 3, 4]

In [20]:
ab=[]
for i in range(len(a)):
    ab.append(a[i]*b[i])
ab    

[5, 12, 12, 36]

In [21]:
import numpy as np

In [22]:
a = np.array([4,5,5])
b = np.array([6,2,5])

In [23]:
a*b

array([24, 10, 25])

# NumPy Array

## Veri tipidir

In [24]:
import numpy as np

In [25]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [26]:
a =np.array([1,2,3,4,5])

In [27]:
type(a)

numpy.ndarray

In [29]:
np.array([3.4,2,3,4,5]) #tektip

array([3.4, 2. , 3. , 4. , 5. ])

In [31]:
np.array([1,2,3,4,5.11] , dtype ="int") #tek tipten kurtulma

array([1, 2, 3, 4, 5])

# sıfırdan array olusturma

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.ones((3,5)) #iki boyutlu array olusturdu

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.full((3,5) ,3) #boyut bilgisini istedigimiz gibi verebiliriz

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [40]:
np.arange(0,31,3) #sıfırdan otuzbire kadar 3er 3er artan dogrusal array olusturduk.ÖNEMLİ

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [42]:
np.linspace(0,1,10)#Belirli aralıkta istediğimiz sayıda değer olusturduk

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [43]:
np.random.normal(10,4,(3,4)) #ortalama ,standart sapma ve boyutu verdiğimiz sayılar olacak sekilde array olusturduk.ÖNEMLİ

array([[12.04340334, 12.04969266,  5.45907777, 11.96638547],
       [10.17426198,  9.67573859,  6.71548738, 15.31274713],
       [11.30701877,  4.8110069 , 13.55152936, 10.73727331]])

In [44]:
np.random.randint(0,10,(3,3))#integerlardan rastgele olusturulmus bir array.ÖNEMLİ

array([[3, 9, 3],
       [1, 3, 8],
       [7, 3, 9]])

# NumPy array özellikleri

* **ndim**: boyut sayısı
* _shape_: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [1]:
import numpy as np

 ## tek boyutlu array

In [3]:
np.random.randint(10,size =10)

array([3, 9, 1, 9, 2, 5, 1, 4, 8, 4])

In [4]:
a =np.random.randint(10,size =10)

In [5]:
a.ndim

1

In [6]:
a.shape #tek boyutlu

(10,)

In [7]:
a.dtype

dtype('int32')

## iki boyutlu array

In [9]:
b =np.random.randint(10,size = (3,5))

In [10]:
b

array([[6, 2, 9, 3, 4],
       [6, 7, 5, 1, 3],
       [4, 9, 6, 2, 5]])

In [11]:
b.ndim

2

In [12]:
b.shape

(3, 5)

In [13]:
a.dtype

dtype('int32')

# RESHAPING

In [14]:
import numpy as np

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a =np.arange(1,10)

In [19]:
a.ndim

1

In [20]:
a.shape

(9,)

In [21]:
a.dtype

dtype('int32')

In [24]:
b =a.reshape((1,9)) #matristir 

In [25]:
b.ndim

2

# Concatenation

In [26]:
import numpy as np

In [27]:
x =np.array ([1,2,3])
y= np.array([4,5,6])

In [29]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [30]:
z = np.array([7,8,9])

In [31]:
np.concatenate([x,y,z]) #arrayleri birleştirdik

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# iki boyut

In [39]:
a= np.array([[1,2,3], 
             [4,5,6]]) #elle iki boyutlu olusturduk

In [41]:
np.concatenate([a,a]) #satır bazında

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.concatenate([a,a],axis =1) #sütunbazında

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting

In [46]:
import numpy as np

In [47]:
x = np.array([1,2,3,99,99,3,2,1])

In [49]:
np.split(x,[3,5]) #n indekse n+1 ayırıyor

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [50]:
a,b,c =np.split(x,[3,5])

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([99, 99])

In [53]:
c

array([3, 2, 1])

# iki boyutlu array ayırma

In [57]:
m = np.arange(16).reshape(4,4)

In [100]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [58]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.vsplit(m,[2]) #ikinci satırdan bölüp dikey olarak yana ekleyelim

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
ust,alt =np.vsplit(m,[2])

In [61]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(m,[2]) #sütundan ayırdı

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
sag,sol =np.hsplit(m,[2])

In [67]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [68]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# SORTING

In [79]:
import numpy as np

In [80]:
v = np.array([2,1,4,3,5])

In [81]:
v

array([2, 1, 4, 3, 5])

In [82]:
np.sort(v) #küçükten büyüğe sıraladı

array([1, 2, 3, 4, 5])

In [83]:
v

array([2, 1, 4, 3, 5])

In [86]:
v.sort()#kalıcı değiştirdi

In [87]:
v

array([1, 2, 3, 4, 5])

 # iki boyutlu sıralama

In [94]:
m =np.random.normal(20,5,(3,3))

In [95]:
m

array([[22.8343232 , 20.36388767, 21.01321254],
       [21.24480299, 22.67707717, 27.22354948],
       [21.18625129, 17.08447741, 21.70822674]])

In [96]:
np.sort(m,axis =1)

array([[20.36388767, 21.01321254, 22.8343232 ],
       [21.24480299, 22.67707717, 27.22354948],
       [17.08447741, 21.18625129, 21.70822674]])

In [97]:
np.sort(m,axis =0)

array([[21.18625129, 17.08447741, 21.01321254],
       [21.24480299, 20.36388767, 21.70822674],
       [22.8343232 , 22.67707717, 27.22354948]])

In [98]:
5*np.array([1,2,3])

array([ 5, 10, 15])

# Index ile elemanlara erişmek

In [102]:
import numpy as np
a =np.random.randint(10,size=10)
a

array([6, 3, 1, 4, 7, 8, 4, 5, 0, 7])

In [103]:
a[0]

6

In [104]:
a[-1]

7

In [105]:
a[0]=100
a

array([100,   3,   1,   4,   7,   8,   4,   5,   0,   7])

# iki boyutlu array üzerinden elemanlara erismek

In [106]:
m =np.random.randint(10,size=(3,5))

In [107]:
m

array([[9, 6, 8, 2, 2],
       [7, 5, 0, 5, 6],
       [9, 3, 1, 3, 7]])

In [108]:
m[0,0]

9

In [114]:
m[2,1] #satır sonra sütun

3

In [115]:
m[2,1]=33

In [116]:
m

array([[ 9,  6,  8,  2,  2],
       [ 7,  5,  0,  5,  6],
       [ 9, 33,  1,  3,  7]])

In [117]:
m[2,1]=2.2
m

array([[9, 6, 8, 2, 2],
       [7, 5, 0, 5, 6],
       [9, 2, 1, 3, 7]])

# Alt küme islemleri /Slicing

In [123]:
import numpy as np
a =np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [124]:
a[0:2]

array([20, 21])

In [125]:
a[:3]

array([20, 21, 22])

In [127]:
a[0::2]#iki iki atlıyo

array([20, 22, 24, 26, 28])

# iki boyutlu slice islemleri

In [135]:
m= np.random.randint(10,size =(5,5))
m

array([[2, 3, 0, 1, 4],
       [7, 0, 2, 9, 6],
       [5, 5, 4, 6, 1],
       [6, 6, 9, 2, 1],
       [6, 5, 8, 0, 1]])

In [136]:
m[:,0]#bütün satırları seç,0.sütun

array([2, 7, 5, 6, 6])

In [139]:
m[2,:]#bütün sütunları sec,2.satır

array([5, 5, 4, 6, 1])

In [140]:
m[0]

array([2, 3, 0, 1, 4])

In [141]:
m[0:2,0:3]

array([[2, 3, 0],
       [7, 0, 2]])

# Arraylerde alt küme üzerinde işlem yapmak(altkümedeki değişiklik ana parçada değişikliklere neden oluyor)

In [2]:
import numpy as np
a =np.random.randint(10,size =(5,5))
a

array([[9, 3, 6, 0, 4],
       [9, 5, 6, 7, 2],
       [5, 6, 4, 3, 8],
       [0, 8, 0, 7, 9],
       [6, 3, 3, 1, 1]])

In [3]:
alt_a =a[0:3,0:2]
alt_a

array([[9, 3],
       [9, 5],
       [5, 6]])

In [4]:
alt_a[0,0] =9999
alt_a[1,1] =8888

In [5]:
alt_a

array([[9999,    3],
       [   9, 8888],
       [   5,    6]])

In [6]:
a

array([[9999,    3,    6,    0,    4],
       [   9, 8888,    6,    7,    2],
       [   5,    6,    4,    3,    8],
       [   0,    8,    0,    7,    9],
       [   6,    3,    3,    1,    1]])

# değişiklik olmaması için (copy() metodu)

In [8]:
alt_b = a[0:3,0:2]

In [9]:
alt_b

array([[9999,    3],
       [   9, 8888],
       [   5,    6]])

In [10]:
alt_b = a[0:3,0:2].copy()

In [11]:
alt_b

array([[9999,    3],
       [   9, 8888],
       [   5,    6]])

In [12]:
a

array([[9999,    3,    6,    0,    4],
       [   9, 8888,    6,    7,    2],
       [   5,    6,    4,    3,    8],
       [   0,    8,    0,    7,    9],
       [   6,    3,    3,    1,    1]])

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Fancy Index ile elemanlara erişmek !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [13]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
v[5]

15

In [16]:
v[3]

9

In [17]:
v[1]

3

In [20]:
[v[1],v[3],v[5]] #tekte aldın reisssss

[3, 9, 15]

In [21]:
al_getir =[1,2,3,5]

In [23]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
v[al_getir]

array([ 3,  6,  9, 15])

# iki boyutta fancy

In [25]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
satir=np.array([0,1])
sütun=np.array([0,1])

In [27]:
m[satir,sütun]

array([0, 4])

# basit index ile fancy index

In [34]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
m[0,[1,2]]

array([1, 2])

# slice ile fancy

In [37]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# kosullu eleman islemleri

In [39]:
import numpy as np
v = np.array([1,2,3,4,5])

In [40]:
v

array([1, 2, 3, 4, 5])

In [41]:
v >5

array([False, False, False, False, False])

In [42]:
v<5

array([ True,  True,  True,  True, False])

In [43]:
v<3

array([ True,  True, False, False, False])

In [44]:
v [v<3] #sorgulama sonucunu cektik(tüm operatorler)

array([1, 2])

In [45]:
v*2

array([ 2,  4,  6,  8, 10])

In [46]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [47]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [48]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel islemler

In [49]:
import numpy as np
v = np.array([1,2,3,4,5])

In [50]:
v -1

array([0, 1, 2, 3, 4])

In [51]:
#ufunc

In [52]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [53]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [55]:
np.multiply(v,5)

array([ 5, 10, 15, 20, 25])

In [56]:
np.divide(v,1)

array([1., 2., 3., 4., 5.])

In [57]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [58]:
v %2

array([1, 0, 1, 0, 1], dtype=int32)

In [59]:
np.mod(v,2) #kalan

array([1, 0, 1, 0, 1], dtype=int32)

In [60]:
np.absolute(np.array([-1,-500]))

array([  1, 500])

In [62]:
np.sin(360)

0.9589157234143065

In [63]:
v = np.array([1,2,3,4])

In [64]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [66]:
np.log2(v)

array([0.       , 1.       , 1.5849625, 2.       ])

In [67]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [72]:
?np #cheatsheet

Object `np #cheatsheet` not found.


# istatiksel hesaplamalar

# Numpy ile İki bilinmeyenli denklem çözümleri

In [76]:
import numpy as np

In [77]:
a =np.array([[5,1],[1,3]])#birinci ve ikinci bilinmeyenlerin katsayilari

In [87]:
b =np.array([12,10]) #neye esit oldukları

In [88]:
a

array([[5, 1],
       [1, 3]])

In [89]:
b

array([12, 10])

In [90]:
x =np.linalg.solve(a,b)

In [91]:
x

array([1.85714286, 2.71428571])